# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: atlas-stats-exporter
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
    goarch:
      - amd64
      - arm
      - arm64
      - '386'
      - s390x
      - ppc64le
      - riscv64
      - mips64
      - mips64le
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w
      - -X 'atlas-stats-exporter/pkg/version.Version={{.Version}}'
      - -X 'atlas-stats-exporter/pkg/version.Commit={{.Commit}}'
      - -X 'atlas-stats-exporter/pkg/version.Date={{.Date}}'
      - -extldflags "-static"
    ignore:
      - goarch: 'arm'
        goos: windows

archives:
  - formats: ['tar.xz']
    files:
        - README.md
    format_overrides:
      - goos: windows
        formats: ['zip']
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
  - id: binary
    formats: [ 'binary' ]
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Version }}-snapshot-{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

signs:
  - artifacts: all
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

sboms:
  - artifacts: archive

release:
  draft: true
  footer: >-
    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).


nfpms:
  - package_name: atlas-stats-exporter
    vendor: Cyb3rJak3
    homepage: https://github.com/Cyb3r-Jak3/atlas-stats-exporter/
    maintainer: Cyb3rJak3 <git@cyberjake.xyz>
    description: >-
      Atlas Stats Exporter is a tool for exporting Atlas stats to various
      backends, including Prometheus. It is designed to be run as a service and
      can be configured via a configuration file or environment variables.
    license: Apache-2.0
    formats:
      - apk
      - deb
      - rpm
    provides:
      - atlas-stats-exporter
    section: default
    priority: extra
    contents:
      - src: LICENSE
        dst: /usr/share/licenses/{{ .ProjectName }}/LICENSE.md
      - src: README.md
        dst: /usr/share/doc/{{ .ProjectName }}/README.md
    builds:
      - default

blobs:
  - provider: s3
    region: auto
    endpoint: https://8be772befd147a8df540aae0fa15c047.r2.cloudflarestorage.com
    bucket: public-files
    ids:
      - default

announce:
  bluesky:
    enabled: true
    username: "releases.cyberjake.xyz"

dockers_v2:
  -
    images:
      - "cyb3rjak3/atlas-exporter"
      - "ghcr.io/cyb3r-jak3/atlas-exporter"
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - "v{{ .Version }}"
      - "latest"
      - "v{{ .Major }}"
      - "{{ .Tag }}"
    labels:
      "org.opencontainers.image.description": "Atlas Stats Exporter is a prometheus exporter for RIPE Atlas"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.vendor": "Cyb3rJak3"
      "org.opencontainers.image.licenses": "Apache-2.0"