{
 "title": "RIPE Atlas",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   {
    "name": "probe",
    "label": "Probe",
    "query": {
     "query": "label_values(atlas_exporter_probe_last_connected,probe_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Credits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "atlas_exporter_credits{job=\"rackspace/atlas-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Probe $probe", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "probe" },
  {
   "title": "Last Connected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "atlas_exporter_probe_last_connected{probe_id=\"$probe\"}",
     "legendFormat": "{{probe_id}}"
    }
   ]
  },
  {
   "title": "Current Probes",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "repeat": "Probe",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "atlas_exporter_probe_measurements{probe_id=\"$probe\"}",
     "legendFormat": "{{type}} - {{status}}"
    }
   ]
  }
 ]
}